# Generated by Django 5.0.6 on 2025-01-02 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('date_time_range', models.JSONField()),
                ('estimated_duration', models.DurationField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('inProgress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('service_type', models.CharField(choices=[('requested', 'Requested'), ('offered', 'Offered')], default='requested', max_length=20)),
                ('applicants', models.ManyToManyField(blank=True, related_name='applied_services', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_services', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='services', to='tags.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FreeService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='JobService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
                ('offered_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('services.service',),
        ),
        migrations.CreateModel(
            name='VolunteeringService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.service')),
            ],
            bases=('services.service',),
        ),
    ]
