# Generated by Django 5.0.6 on 2025-01-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='publisher',
            new_name='user',
        ),
    ]
