# Generated by Django 5.0.6 on 2025-01-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('provider', 'Provider'), ('publisher', 'Publisher')], default='publisher', max_length=20),
        ),
    ]
