# Generated by Django 5.0.6 on 2025-01-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_publisher_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='offered_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
