# Generated by Django 5.0.6 on 2025-01-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('location_range', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='tags.tag')),
            ],
        ),
    ]
