# Generated by Django 5.0.6 on 2025-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
        ('tags', '0002_specialisttag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='service_tag',
        ),
        migrations.AddField(
            model_name='specialist',
            name='service_tags',
            field=models.ManyToManyField(related_name='specialists', to='tags.specialisttag'),
        ),
    ]
