# Generated by Django 5.0.6 on 2025-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expo_push_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='expo_push_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
