# Generated by Django 5.0.6 on 2024-12-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_img',
        ),
    ]
