# Generated by Django 5.0.6 on 2025-04-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_badges', '0001_initial'),
        ('users', '0005_customuser_referral_code_customuser_referred_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, to='new_badges.badge'),
        ),
    ]
