# Generated by Django 5.0.6 on 2025-04-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_badges', '0001_initial'),
        ('users', '0006_remove_profile_badges_customuser_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='new_badges.badge'),
        ),
    ]
