# Generated by Django 5.0.6 on 2025-04-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badges',
        ),
    ]
