# Generated by Django 5.0.6 on 2025-04-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
    ]
