const nearbyCities: Record<string, string[]> = {
  "Jerusalem": ["Mevaseret Zion", "Beit Shemesh", "Ma'ale Adumim", "Modi'in", "Giv'at Ze'ev", "Jerusalem"],
  "Tel Aviv": ["Ramat Gan", "Givatayim", "Bat Yam", "Holon", "Bnei Brak", "Ramat HaSharon", "Tel Aviv"],
  "Haifa": ["Nesher", "Tirat Carmel", "Kiryat Motzkin", "Kiryat Bialik", "Kiryat Yam", "Kiryat Ata", "Yokneam", "Acre (Akko)", "Haifa"],
  "Be'er Sheva": ["Omer", "Meitar", "Lehavim", "Rahath", "Ofakim", "Netivot", "Dimona", "Arad", "Kiryat Gat", "Be'er Sheva"],
  "Yokneam": ["Haifa", "Nesher", "Megiddo", "Jezreel Valley", "Yokneam"],

  "Dimona": ["Yeruham", "Arad", "Be'er Sheva", "Mitzpe Ramon", "Dimona"],
  "Arad": ["Dimona", "Be'er Sheva", "Arad", "Yeruham"],
  "Yeruham": ["Dimona", "Mitzpe Ramon", "Arad", "Yeruham"],
  "Mitzpe Ramon": ["Yeruham", "Dimona", "Mitzpe Ramon"],
  "Kiryat Gat": ["Be'er Sheva", "Netivot", "Ashkelon", "Sderot", "Kiryat Gat"],
  "Netivot": ["Ofakim", "Sderot", "Rahath", "Ashkelon", "Kiryat Gat", "Netivot", "Be'er Sheva"],
  "Rahath": ["Be'er Sheva", "Netivot", "Ofakim", "Rahath"],
  "Ofakim": ["Netivot", "Sderot", "Rahath", "Be'er Sheva", "Ofakim"],
  "Sderot": ["Netivot", "Ofakim", "Ashkelon", "Kiryat Gat", "Sderot"],
  "Ashkelon": ["Ashdod", "Sderot", "Netivot", "Kiryat Gat", "Ashkelon"],
  "Ashdod": ["Ashkelon", "Yavne", "Rehovot", "Rishon LeZion", "Ashdod"],

  "Yavne": ["Ashdod", "Rehovot", "Ness Ziona", "Yavne"],
  "Rehovot": ["Ness Ziona", "Yavne", "Rishon LeZion", "Rehovot"],
  "Ness Ziona": ["Rehovot", "Yavne", "Rishon LeZion", "Be'er Ya'akov", "Ness Ziona"],
  "Rishon LeZion": ["Holon", "Bat Yam", "Rehovot", "Ness Ziona", "Tel Aviv", "Be'er Ya'akov", "Rishon LeZion"],
  "Holon": ["Bat Yam", "Rishon LeZion", "Tel Aviv", "Holon"],
  "Bat Yam": ["Holon", "Tel Aviv", "Rishon LeZion", "Bat Yam"],
  "Ramat Gan": ["Tel Aviv", "Givatayim", "Bnei Brak", "Ramat Gan"],
  "Givatayim": ["Tel Aviv", "Ramat Gan", "Bnei Brak", "Givatayim"],
  "Bnei Brak": ["Ramat Gan", "Givatayim", "Petah Tikva", "Bnei Brak"],
  "Petah Tikva": ["Bnei Brak", "Rosh HaAyin", "Kiryat Ono", "El'ad", "Petah Tikva"],
  "Kiryat Ono": ["Petah Tikva", "Givat Shmuel", "Yehud", "Kiryat Ono"],
  "Givat Shmuel": ["Kiryat Ono", "Bnei Brak", "Givat Shmuel"],
  "Yehud": ["Kiryat Ono", "Or Yehuda", "Yehud"],
  "Or Yehuda": ["Yehud", "Lod", "Or Yehuda"],
  "Lod": ["Ramla", "Modi'in", "Or Yehuda", "Shoham", "Lod"],
  "Ramla": ["Lod", "Modi'in", "Be'er Ya'akov", "Ramla"],
  "Be'er Ya'akov": ["Ramla", "Rishon LeZion", "Ness Ziona", "Be'er Ya'akov"],
  "Modi'in": ["Lod", "Ramla", "Shoham", "Jerusalem", "Modi'in"],
  "Shoham": ["Modi'in", "El'ad", "Lod", "Shoham"],
  "El'ad": ["Shoham", "Petah Tikva", "Rosh HaAyin", "El'ad"],
  "Rosh HaAyin": ["Petah Tikva", "El'ad", "Kfar Saba", "Rosh HaAyin"],

  "Kfar Saba": ["Rosh HaAyin", "Hod Hasharon", "Ra'anana", "Kfar Saba"],
  "Ra'anana": ["Kfar Saba", "Herzliya", "Hod Hasharon", "Ra'anana"],
  "Herzliya": ["Ra'anana", "Ramat HaSharon", "Netanya", "Herzliya"],
  "Ramat HaSharon": ["Herzliya", "Tel Aviv", "Ramat HaSharon"],
  "Hod Hasharon": ["Kfar Saba", "Ra'anana", "Hod Hasharon"],
  "Netanya": ["Herzliya", "Even Yehuda", "Kfar Yona", "Netanya"],
  "Even Yehuda": ["Netanya", "Kfar Yona", "Even Yehuda"],
  "Kfar Yona": ["Netanya", "Even Yehuda", "Hadera", "Kfar Yona"],
  "Hadera": ["Kfar Yona", "Pardes Hanna", "Binyamina", "Caesarea", "Or Akiva", "Hadera"],
  "Pardes Hanna": ["Hadera", "Binyamina", "Zikhron Ya'akov", "Pardes Hanna"],
  "Binyamina": ["Pardes Hanna", "Zikhron Ya'akov", "Binyamina"],
  "Zikhron Ya'akov": ["Binyamina", "Pardes Hanna", "Caesarea", "Zikhron Ya'akov"],
  "Caesarea": ["Zikhron Ya'akov", "Or Akiva", "Hadera", "Caesarea"],
  "Or Akiva": ["Caesarea", "Hadera", "Or Akiva"],

  "Tirat Carmel": ["Haifa", "Nesher", "Tirat Carmel"],
  "Nesher": ["Haifa", "Tirat Carmel", "Yokneam", "Nesher"],
  "Kiryat Motzkin": ["Kiryat Bialik", "Haifa", "Kiryat Motzkin"],
  "Kiryat Bialik": ["Kiryat Motzkin", "Kiryat Yam", "Haifa", "Kiryat Ata", "Kiryat Bialik"],
  "Kiryat Yam": ["Kiryat Bialik", "Haifa", "Kiryat Yam"],
  "Kiryat Ata": ["Haifa", "Kiryat Bialik", "Kiryat Ata"],
  "Acre (Akko)": ["Nahariya", "Karmiel", "Haifa", "Acre (Akko)"],
  "Nahariya": ["Acre (Akko)", "Ma'alot-Tarshiha", "Nahariya"],
  "Ma'alot-Tarshiha": ["Nahariya", "Karmiel", "Ma'alot-Tarshiha"],
  "Karmiel": ["Ma'alot-Tarshiha", "Acre (Akko)", "Tzfat (Safed)", "Karmiel"],
  "Tzfat (Safed)": ["Karmiel", "Rosh Pina", "Tzfat (Safed)"],
  "Rosh Pina": ["Tzfat (Safed)", "Hatzor HaGlilit", "Rosh Pina"],
  "Tiberias": ["Yavne'el", "Migdal", "Afula", "Tiberias"],
  "Afula": ["Tiberias", "Nazareth", "Migdal HaEmek", "Beit She'an", "Afula"],
  "Nazareth": ["Afula", "Nazareth Illit", "Migdal HaEmek", "Nazareth"],
  "Nazareth Illit": ["Nazareth", "Migdal HaEmek", "Nazareth Illit"],
  "Migdal HaEmek": ["Afula", "Nazareth", "Nazareth Illit", "Migdal HaEmek"],
  "Beit She'an": ["Afula", "Tiberias", "Beit She'an"],
  "Migdal": ["Tiberias", "Migdal"],

  "Eilat": ["Yotvata", "Be’er Ora", "Timna", "Eilat"],
  "Yotvata": ["Eilat", "Be’er Ora", "Yotvata"],
  "Be’er Ora": ["Eilat", "Yotvata", "Be’er Ora"],
  "Timna": ["Eilat", "Timna"],

  "Beit Shemesh": ["Jerusalem", "Mevaseret Zion", "Beit Shemesh"],
  "Giv'at Ze'ev": ["Jerusalem", "Giv'at Ze'ev"],
  "Lehavim": ["Be'er Sheva", "Meitar", "Omer", "Lehavim"],
  "Ma'ale Adumim": ["Jerusalem", "Ma'ale Adumim"],
  "Megiddo": ["Yokneam", "Megiddo"],
  "Meitar": ["Be'er Sheva", "Lehavim", "Omer", "Meitar"],
  "Mevaseret Zion": ["Jerusalem", "Beit Shemesh", "Mevaseret Zion"],
  "Omer": ["Be'er Sheva", "Lehavim", "Meitar", "Omer"],
  "Yavne'el": ["Tiberias", "Yavne'el"]
};




export default nearbyCities;
