export const cityAliases: Record<string, string> = {
  "acre akko": "Acre (Akko)",
  "afula": "Afula",
  "arad": "Arad",
  "ashdod": "Ashdod",
  "ashkelon": "Ashkelon",
  "bat yam": "Bat Yam",
  "beer ora": "Be'er Ora",
  "beer sheva": "Be'er Sheva",
  "beersheva": "Be'er Sheva",
  "beersheba": "Be'er Sheva",
  "beer sheba": "Be'er Sheva",
  "beer yaakov": "Be'er Ya'akov",
  "beeryaakov": "Be'er Ya'akov",
  "beit shean": "Beit She'an",
  "beitshean": "Beit She'an",
  "beit shemesh": "Beit Shemesh",
  "beitshemesh": "Beit Shemesh",
  "binyamina": "Binyamina",
  "bnei brak": "Bnei Brak",
  "bneibrak": "Bnei Brak",
  "caesarea": "Caesarea",
  "dimona": "Dimona",
  "eilat": "Eilat",
  "elad": "El'ad",
  "even yehuda": "Even Yehuda",
  "evenyehuda": "Even Yehuda",
  "givat zeev": "Giv'at Ze'ev",
  "givatzeev": "Giv'at Ze'ev",
  "givat shmuel": "Givat Shmuel",
  "givatshmuel": "Givat Shmuel",
  "givatayim": "Givatayim",
  "haifa": "Haifa",
  "hadera": "Hadera",
  "herzliya": "Herzliya",
  "hod hasharon": "Hod Hasharon",
  "hodhasharon": "Hod Hasharon",
  "holon": "Holon",
  "jerusalem": "Jerusalem",
  "karmiel": "Karmiel",
  "kfar saba": "Kfar Saba",
  "kfarsaba": "Kfar Saba",
  "kfar yona": "Kfar Yona",
  "kfaryona": "Kfar Yona",
  "kiryat ata": "Kiryat Ata",
  "kiryatata": "Kiryat Ata",
  "kiryat bialik": "Kiryat Bialik",
  "kiryatbialik": "Kiryat Bialik",
  "kiryat gat": "Kiryat Gat",
  "kiryatgat": "Kiryat Gat",
  "kiryat motzkin": "Kiryat Motzkin",
  "kiryatmotzkin": "Kiryat Motzkin",
  "kiryat ono": "Kiryat Ono",
  "kiryatono": "Kiryat Ono",
  "kiryat yam": "Kiryat Yam",
  "kiryatyam": "Kiryat Yam",
  "lehavim": "Lehavim",
  "lod": "Lod",
  "maale adumim": "Ma'ale Adumim",
  "maaleadumim": "Ma'ale Adumim",
  "maalottarshiha": "Ma'alot-Tarshiha",
  "maalot tarshiha": "Ma'alot-Tarshiha",
  "megiddo": "Megiddo",
  "meitar": "Meitar",
  "mevaseret zion": "Mevaseret Zion",
  "mevaseretzion": "Mevaseret Zion",
  "migdal": "Migdal",
  "migdal haemek": "Migdal HaEmek",
  "migdalhaemek": "Migdal HaEmek",
  "mitzpe ramon": "Mitzpe Ramon",
  "mitzperamon": "Mitzpe Ramon",
  "modiin": "Modi'in",
  "modin": "Modi'in",
  "nahariya": "Nahariya",
  "nazareth": "Nazareth",
  "nazareth illit": "Nazareth Illit",
  "nazarethillit": "Nazareth Illit",
  "nesher": "Nesher",
  "ness ziona": "Ness Ziona",
  "nessziona": "Ness Ziona",
  "netanya": "Netanya",
  "netivot": "Netivot",
  "omer": "Omer",
  "or akiva": "Or Akiva",
  "orakiva": "Or Akiva",
  "or yehuda": "Or Yehuda",
  "oryehuda": "Or Yehuda",
  "pardes hanna": "Pardes Hanna",
  "pardeshanna": "Pardes Hanna",
  "petah tikva": "Petah Tikva",
  "petachtikva": "Petah Tikva",
  "petaktikva": "Petah Tikva",
  "raanana": "Ra'anana",
  "rahath": "Rahath",
  "ramla": "Ramla",
  "ramat gan": "Ramat Gan",
  "ramatgan": "Ramat Gan",
  "ramat hasharon": "Ramat HaSharon",
  "ramathasharon": "Ramat HaSharon",
  "rehovot": "Rehovot",
  "rishon lezion": "Rishon LeZion",
  "rishonlezion": "Rishon LeZion",
  "rosh haayin": "Rosh HaAyin",
  "roshhaayin": "Rosh HaAyin",
  "rosh pina": "Rosh Pina",
  "roshpina": "Rosh Pina",
  "sederot": "Sderot",
  "sderot": "Sderot",
  "shoham": "Shoham",
  "tel aviv": "Tel Aviv",
  "telaviv": "Tel Aviv",
  "tel aviv yafo": "Tel Aviv",
  "tel aviv-yafo": "Tel Aviv",
  "telavivyafo": "Tel Aviv",
  "tiberias": "Tiberias",
  "timna": "Timna",
  "tirat carmel": "Tirat Carmel",
  "tiratcarmel": "Tirat Carmel",
  "tzfat safed": "Tzfat (Safed)",
  "tzfatsafed": "Tzfat (Safed)",
  "yavne": "Yavne",
  "yavneel": "Yavne'el",
  "yehud": "Yehud",
  "yeruham": "Yeruham",
  "yokneam": "Yokneam",
  "yotvata": "Yotvata",
  "zikhron yaakov": "Zikhron Ya'akov",
  "zikhronyaakov": "Zikhron Ya'akov",
  "zichron yaakov": "Zikhron Ya'akov"
};
