export const cityAliases: Record<string, string> = {
    "acre akko": "Acre (Akko)",
    "afula": "Afula",
    "arad": "Arad",
    "ashdod": "Ashdod",
    "ashkelon": "Ashkelon",
    "bat yam": "Bat Yam",
    "beer ora": "Be'er Ora",
    "beer sheva": "Be'er Sheva",
    "beer yaakov": "Be'er Ya'akov",
    "beit shean": "Beit She'an",
    "beit shemesh": "Beit Shemesh",
    "binyamina": "Binyamina",
    "bnei brak": "Bnei Brak",
    "caesarea": "Caesarea",
    "dimona": "Dimona",
    "eilat": "Eilat",
    "elad": "El'ad",
    "even yehuda": "Even Yehuda",
    "givat zeev": "Giv'at Ze'ev",
    "givat shmuel": "Givat Shmuel",
    "givatayim": "Givatayim",
    "haifa": "Haifa",
    "hadera": "Hadera",
    "herzliya": "Herzliya",
    "hod hasharon": "Hod Hasharon",
    "holon": "Holon",
    "jerusalem": "Jerusalem",
    "karmiel": "Karmiel",
    "kfar saba": "Kfar Saba",
    "kfar yona": "Kfar Yona",
    "kiryat ata": "Kiryat Ata",
    "kiryat bialik": "Kiryat Bialik",
    "kiryat gat": "Kiryat Gat",
    "kiryat motzkin": "Kiryat Motzkin",
    "kiryat ono": "Kiryat Ono",
    "kiryat yam": "Kiryat Yam",
    "lehavim": "Lehavim",
    "lod": "Lod",
    "maale adumim": "Ma'ale Adumim",
    "maalottarshiha": "Ma'alot-Tarshiha",
    "megiddo": "Megiddo",
    "meitar": "Meitar",
    "mevaseret zion": "Mevaseret Zion",
    "migdal": "Migdal",
    "migdal haemek": "Migdal HaEmek",
    "mitzpe ramon": "Mitzpe Ramon",
    "modiin": "Modi'in",
    "nahariya": "Nahariya",
    "nazareth": "Nazareth",
    "nazareth illit": "Nazareth Illit",
    "nesher": "Nesher",
    "ness ziona": "Ness Ziona",
    "netanya": "Netanya",
    "netivot": "Netivot",
    "omer": "Omer",
    "or akiva": "Or Akiva",
    "or yehuda": "Or Yehuda",
    "pardes hanna": "Pardes Hanna",
    "petah tikva": "Petah Tikva",
    "raanana": "Ra'anana",
    "rahath": "Rahath",
    "ramla": "Ramla",
    "ramat gan": "Ramat Gan",
    "ramat hasharon": "Ramat HaSharon",
    "rehovot": "Rehovot",
    "rishon lezion": "Rishon LeZion",
    "rosh haayin": "Rosh HaAyin",
    "rosh pina": "Rosh Pina",
    "sderot": "Sderot",
    "shoham": "Shoham",
    "tel aviv": "Tel Aviv",
    "tiberias": "Tiberias",
    "timna": "Timna",
    "tirat carmel": "Tirat Carmel",
    "tzfat safed": "Tzfat (Safed)",
    "yavne": "Yavne",
    "yavneel": "Yavne'el",
    "yehud": "Yehud",
    "yeruham": "Yeruham",
    "yokneam": "Yokneam",
    "yotvata": "Yotvata",
    "zikhron yaakov": "Zikhron Ya'akov"
  };
  